[build]
  command = "node build.js"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
